name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: "19 15 * * *"
  push:
    branches: ["main"]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  list-files:
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.devcontainer-folders.outputs.folders }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get devcontainer folders
        id: devcontainer-folders
        run: echo "folders=$(ls src | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: list-files
    strategy:
      matrix:
        folder: ${{ fromJson(needs.list-files.outputs.folders) }}
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get lowercase repo name
        id: lowercase-repo
        run: echo "repo=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: src/${{ matrix.folder }}
          imageName: ${{ env.REGISTRY }}/${{ steps.lowercase-repo.outputs.repo }}/${{ matrix.folder }}
          cacheFrom: ${{ env.REGISTRY }}/${{ steps.lowercase-repo.outputs.repo }}/${{ matrix.folder }}
          refFilterForPush: "refs/heads/main"
